version: '3'

volumes:
  media:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: praetorian15/foodgram_backend
    env_file: .env
    volumes:
      - media:/media
      - static:/backend_static
    depends_on:
      - db
  frontend:
    env_file: .env
    image: praetorian15/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: praetorian15/foodgram_gateway
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - media:/media
      - static:/static
    depends_on:
      - backend
      - frontend
