version: '3.3'

services:
  db:
    image: postgres:13
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: praetorian15/foodgram_backend
    env_file: ../.env
    volumes:
      - ../media_val:/app/media
      - ../static_val:/app/static
      - ../redoc_val:/app/api/docs/
    depends_on:
      - db
    restart: always

  frontend:
    image: praetorian15/foodgram_frontend
    env_file: ../.env
    volumes:
      - ../frontend:/app/result_build/

  nginx:
    container_name: foodgram-nginx
    image: nginx:1.19.3
    env_file: ../.env
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - media_val:/usr/share/nginx/html/media/
      - redoc_val:/usr/share/nginx/html/api/docs/
      - static_val:/usr/share/nginx/html/static/
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  media_val:
  pg_data:
  static_val:
  redoc_val:
