version: '3.3'

services:
  db:
    image: postgres:13
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: praetorian15/foodgram_backend
    env_file: ../.env
    volumes:
      - ../media:/app/media
      - ../static:/static
      - ../docs:/app/docs
    depends_on:
      - db

  frontend:
    image: praetorian15/foodgram_frontend
    env_file: ../.env
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: foodgram-nginx
    image: nginx:1.19.3
    env_file: ../.env
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../static:/usr/share/nginx/html/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ../media:/usr/share/nginx/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  media:
  pg_data:
  static:
