version: '3.3'

volumes:
  media:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: praetorian15/foodgram_backend
    env_file: .env
    volumes:
      - ./media:/media
      - ./static:/backend_static
    depends_on:
      - db

  frontend:
    image: praetorian15/foodgram_frontend
    env_file: .env
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - ./media:/etc/nginx/html/media/
      - ./static:/etc/nginx/html/static/
    depends_on:
      - backend
      - frontend
