# Generated by Django 3.2.3 on 2023-08-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='recipes', to='recipes.Tag', verbose_name='Тэг'),
        ),
    ]
