# Generated by Django 3.2.3 on 2023-09-09 13:11

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#0000FF', 'Синий'), ('#008000', 'Зеленый'), ('#800080', 'Фиолетовый')], default='#FFFFFF', image_field=None, max_length=7, samples=None, verbose_name='Цвет'),
        ),
    ]
