# Generated by Django 3.2.3 on 2023-09-02 17:38

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[core.validators.validate_username], verbose_name='Имя пользователя'),
        ),
    ]
